spring:
  datasource:
    db1: 
      url: jdbc:mysql://localhost:3306/db1?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
    db2: 
      url: jdbc:mysql://localhost:3306/db2?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      
      
    
